version: '3.9'
services:
  
  db:
    container_name: Database
    image: postgres:alpine
    volumes:
      - ./data:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=verystrongpasswd
      - PGDATA=/var/lib/pgsql/data/pgdata

  app:
    container_name: Web-app
    build: ./app
    command: bash -c "python manage.py makemigrations &&
            python manage.py migrate && python manage.py collectstatic --noinput &&
            uwsgi --ini uwsgi.ini"
    volumes:
      - ./app:/app
      - ./socket:/socket
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=verystrongpasswd
    expose:
      - "8001"
    depends_on:
      - db

  nginx:
    container_name: NGINX
    build: ./nginx
    volumes:
      - ./app/static:/mysite/static
      - ./app/media:/mysite/media
      - ./socket:/socket
    ports:
      - "8001:80"
    depends_on:
      - db
      - app
